config/routes.rb
Talkie::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resource :dashboard do 
    
  end
  
  resource :settings, :only => [:show, :create] do 
    get :remove
  end
  
  resources :sites do 
    member do 
      get :setup
      get :settings
      get :remove
    end    
  end
  
  resources :chats do 
    
  end
  
  match '/base' => "api#base"

  root :to => 'public#index'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  before_filter :login_required
  
  def index
    
  end
  
  # Update settings for the user, including avatar
  def create
    if @current_user.update_attributes(params[:user])
      flash[:notice] = "Settings update"
    else
      logger.info @current_user.errors.inspect
      flash[:error] = "We could not update the settings right now, try again!"
    end
    redirect_to settings_path and return
  end
  
  def remove
    @current_user.update_attribute(:avatar, nil)
    redirect_to settings_path and return
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/show.html.erb
<!-- Secondary navigation -->
<nav id="secondary">
	<ul>
	</ul>
</nav>

<!-- The content -->
<section id="content">
	<h2>Settings</h2>
	<%= form_tag settings_path, {:multipart => true} do %>

	<div class="column left third">
		
		<% if @current_user.avatar.file? %>
			<img src="<%= @current_user.avatar.url(:edit) %>" class="edit-avatar"/>
			<center>
				<a href="<%= remove_settings_path %>">Remove</a>
			</center>
		<% else %>
			<img src="/avatar/missing.jpg" class="edit-avatar">		
		<% end %>
		<section class="first-child">
			<label for="avatar">
				Avatar
			</label>
			<div>
				<input type="file" name="user[avatar]" />
			</div>	
		</section>
		
	</div>

	<div class="column right twothird">
			<section class="first-child">
				<label for="username">
					Username
				</label>
				<div>
					<input id="username" name="user[login]" type="text" placeholder="<%= @current_user.login %>" value="<%= @current_user.login %>" class="required" />
				</div>			
			</section>
			
			<section>
					<label for="email">
						Email
					</label>
					<div>
						<input id="email" name="user[email]" type="text" placeholder="<%= @current_user.email %>" value="<%= @current_user.email %>" class="required" />
					</div>								
			</section>
			
			<section>
					<label for="email">
						Password
					</label>
					<div>
						<input id="email" name="user[password]" type="password" />
					</div>								
			</section>
			
			<section>
					<label for="email">
						Confirm password
					</label>
					<div>
						<input id="email" name="user[password_confirmation]" type="password" />
					</div>								
			</section>
			
			
			<section>
				<p>
			    <input type="submit" class="button primary submit" value="Submit" />
			    <a href="/dashboard" class="button">Cancel</a>
			  </p>
			</section>
			
	</div>
	
	<% end %>


</section>


<% content_for :stylesheets do %>
	<%= stylesheet_link_tag 'settings' %>
<% end %>