config/routes.rb
Talkie::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resource :dashboard do 
    
  end
  
  resource :settings, :only => [:show, :create] do 
    get :remove
  end
  
  resources :sites do 
    member do 
      get :setup
      get :settings
      get :remove
    end    
  end
  
  resources :chats do 
    
  end
  
  match '/base' => "api#base"

  root :to => 'public#index'
end

app/models/site.rb
##### Author: Daniel Sundström  #####
##### Date: August 21, 2011 - Aug:08:58#####
##### License: MIT License    #####
require 'digest/sha1'
class Site < ActiveRecord::Base
  
  # When creating a site, make sure we generate a proper subdomain and an authorizationhash
  before_create :set_subdomain, :make_auth_hash  
  # Ensure we don't have two sites with same unique subdomain
  validates_uniqueness_of :subdomain
  # Remove redis-based data for this site when deleting it
  before_destroy :cleanup
  # Set the redis-key on after_commit to make sure the ID is properly set
  after_commit :set_redis_key

  # Format a redis-compliant key with the provded suffix
  def key(spec)
    return "site-#{self.subdomain.to_s}-#{spec.to_s}"
  end
  
  # Load the last 10 messages for this site from redis, parse the JSON (redis can only store strings, 
  # all data is stored as JSON), and parse the timestamp to a proper Ruby Time-object. Finally, reverse the list
  # since the datastructure in redis will be sorted created_at, while we want created_at desc since we grad from head of list
  def messages(limit=10)
    $redis.lrange(key('messages'), 0, 10).map{|a| b = JSON.parse(a); b['date'] = Time.at(b['timestamp'].to_i/1000); b }.reverse
  end
  
  # Do not load currently online users from Redis at the moment, since we can't render it properly. 
  # In order to keep public class API, return an empty list
  def users
    []
  end
  
  private
  
  # Take the name of the site, and format it in an UTF8-intelligent way (converting for example davén to daven), downcase it
  # and use it as the subdomain
  def set_subdomain
    self.subdomain = name.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/,'').gsub(/[^\s\w\d]/, "").gsub(/\s+/, "-").downcase.to_s
  end

  # Calculate a random SHA1-hash to use as unique identifier for this specific site-object, globally across all versions of Talkie
  def make_auth_hash
    self.auth_hash = Digest::SHA1.hexdigest(self.object_id.to_s + Time.now.to_i.to_s + self.name.to_s)
  end

  # Store a representation of this site in redis as a hash-object, since NodeJS will require it to access the site,
  # validate it and route messages to it properly
  def set_redis_key
    $redis.hmset key('chat'), 
      'active', 1, 
      'site_id', self.id, 
      'user_id', self.user_id, 
      'site_name', self.name, 
      'authkey', self.auth_hash
  end

  # When deleting a site, remove the representations of it from redis
  def cleanup
    $redis.del key('chat')
    $redis.del key('messages')
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  before_filter :login_required
  
  # Load entire list of all sites owned by the user and render them
  def index
    @sites  = @current_user.sites.all
  end
  
  # Create a new site with provided data
  def create
    site    = @current_user.sites.create(params[:site]) 
    if site && site.errors.empty? 
      redirect_to setup_site_path(site) and return
    else
      redirect_to :back and return
    end
  end

  # Display the script-tag for the currently chosen site
  def setup
    @site   = @current_user.sites.find(params[:id])
  end
  
  # Delete the site
  def remove
    site = @current_user.sites.find(params[:id])
    if site && site.destroy
      flash[:notice] = "Site removed"
    else
      flash[:error] = "Couldn't remove site"
    end
    redirect_to :back and return
  end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_tag sites_path, {:class => "validate"} do %>
	<section class="first-child">
		<label for="name">
			Name
		</label>
		<div>
			<input type="text" name="site[name]" placeholder="Name" class="required"/>
		</div>
	</section>

	<section class="first-child">
		<label for="name">
			Host
		</label>
		<div>
			<input type="text" name="site[host]" placeholder="http://example.com" class="required"/>
		</div>
	</section>
	
	<section>
		<p>
	    <input type="submit" class="button primary submit big" value="Create" />
	  </p>
	</section>			
<% end %>

app/views/sites/index.html.erb
<!-- The content -->
<section id="content">
	
	<h2>Sites</h2>
	
	<div class="column left third">
		<strong>site</strong> <em>noun, verb</em>, sit-ed, sit-ing<br />
		<em>noun</em>
		<br /><br />
		<ol>
			<li>
				the position or location of a town, building, etc., especially as to its environment: <em>the site of our summer cabin</em>.
			</li>
			<li>
				the area or exact plot of ground on which anything is, has been, or is to be located: <em>the site of ancient Troy</em>.
			</li>	
			<li>
				Computers. <em>Web site</em>.
			</li>	
		</ol>	
	</div>
	
	<div class="column right twothird">
		<% unless @sites.empty? %>
		<table class="">
	  	<thead>
	      <tr>
	        <th>Name</th>
	        <th>Host</th>
	        <th>Actions</th>
	      </tr>
	    </thead>
			<tbody>
				<% @sites.each do |site| %>
				<tr>
					<td>
						<%= site.name %>
					</td>
					<td>
						<%= site.host %>
					</td>
					<td>
						<span class="button-group">
	            <a href="<%= remove_site_path(site) %>" class="button icon remove danger">Remove</a>
	          </span>	          
					</td>	
				</tr>
				<% end %>
			</tbody>
		</table>
		<br />
		<h4>Add Site</h4>
		<p>

		</p>	
		<%= render :partial => 'form' %>
		
		
		<% else %>
		
			<h1>No sites yet?</h1>
			<br />
			<p>
				In order to start using Talkie, just add a new site below, and then paste the generated 
				code into your website. We'll automatically start everything and you'll be talking to your
				customers in no time!
			</p>
			
			<%= render :partial => 'form' %>

		<% end %>
	</div>


</section>

app/views/sites/setup.html.erb
<!-- The content -->
<section id="content">
	
	<h2>Sites</h2>
	
	<div class="column left third">
		<h3>Tips</h3>
		<ul>
			<li>
				Paste the script just before the end of the body-tag to 
				make the page load as fast as possible
			</li>	
			<br />
			<li>
				Make sure you paste the code exactly as shown, any differences will
				make it impossible for us to load your chat correctly
			</li>	
			<br />
			<li>
				You can always reconfigure your site later on, changing hooks and 
				rules from the <a href="<%= settings_site_path(@site) %>">settings page</a>
			</li>	
		</ul>	
	</div>
	
	<div class="column right twothird">

			<h1>1. Integrate with your site</h1>
			<br />
			<p>
				In order to start using Talkie, just add a new site below, and then paste the generated 
				code into your website. We'll automatically start everything and you'll be talking to your
				customers in no time!
			</p>
			<pre>&lt;script type="text/javascript" src="http://<%= configatron.base.url %>/base.js?h=<%= @site.auth_hash %>"&gt;&lt;/script&gt;</pre>	
			<div style="margin:-12px 0px 0px 0px;font-size:11px;cursor:pointer">Copy to clipboard</div>
			<br /><br />

			<div class="button-group">
				<a href="<%= site_path(@site) %>" class="button primary">Okay, I'm done</a>
				<a href="/help/integration/script-tag" class="button">I need help with this!</a>				
			</div>
		<br style="clear:both"/><br />
	</div>


</section>